### ISSUE TITLE
Automatically check PR using GitHub Actions

### ISSUE THREAD

**Issue by takanakahiko** [takanakahiko/slack-emoji-meister#15]
This repo's reviewer is only me.

I am a beginner of Javascript and may make a mistake in review.
Testing lint and build should be run automatically.

I plan to use GitHub Actions.

**Comment by takanakahiko** [comment]
I was misunderstanding.
We can't use GitHub Actions in public repository.

https://help.github.com/articles/creating-a-workflow-with-github-actions/
> You can create actions for your own use in private repositories or to share with others in public repositories. During the limited public beta, you can only configure workflows in private repositories.

So, We need to consider other methods.

**Comment by potato4d** [comment]
use CircleCI?

**Comment by takanakahiko** [comment]
Umm... 
I wanted to create a model case for GitHub Actions, but let's use CircleCI until release GitHub Actions.
Do you have any other simpler alternatives?

**Comment by takanakahiko** [comment]
I did it!
