### ISSUE TITLE
stop using standard or make lint rules compliant

### ISSUE THREAD

**Issue by uneco** [takanakahiko/slack-emoji-meister#27]
An error occurs in my environment, but `npm run lint` do not return error.

<img width="529" alt="2019-01-20 0 38 33" src="https://user-images.githubusercontent.com/603523/51428846-e6b11280-1c4b-11e9-964d-54e98f9058ce.png">
<img width="527" alt="2019-01-20 0 38 39" src="https://user-images.githubusercontent.com/603523/51428847-e749a900-1c4b-11e9-8e18-a3ca9c490a4e.png">

This is due to conflict between tslint.json and `standard`.

package.json
```package.json
 18     "lint": "standard && tsc --noEmit && tslint ./app/scripts/**/*.ts --fix"
```
any ideas?

**Comment by takanakahiko** [comment]
`standard` is used for `tasks`.
Is it possible to solve by limiting the scope to `./tasks` only?

**Comment by uneco** [comment]
okay, how about remove the `standard && ` from `lint` task in the `package.json`?

**Comment by takanakahiko** [comment]
I think it should be edited like this.
`standard "tasks/**/*.js"`

**Comment by uneco** [comment]
just as you said.
