### ISSUE TITLE
s/team/workspace/ ?

### ISSUE THREAD

**Issue by uneco** [takanakahiko/slack-emoji-meister#28]
Slack does not currently use the name “team” and instead uses the name “workspace”.

https://get.slack.help/hc/en-us/articles/115004071768-What-is-Slack-

<img width="671" alt="2019-01-20 1 06 49" src="https://user-images.githubusercontent.com/603523/51429203-b79ca000-1c4f-11e9-833d-4c9d514f03d0.png">

**Comment by takanakahiko** [comment]
That's right! We should replace it now.
