### ISSUE TITLE
save the slack workspace and choose a workspace in the context menu

### ISSUE THREAD

**Issue by uneco** [takanakahiko/slack-emoji-meister#29]
**Is your feature request related to a problem? Please describe.**
No, Just a new feature. (template mismatch?)

~**Describe the solution you'd like**~
~A clear and concise description of what you want to happen.~

~**Describe alternatives you've considered**~
~A clear and concise description of any alternative solutions or features you've considered.~

~**Additional context**~
~Add any other context or screenshots about the feature request here.~

I already implemented this feature.
Once the user enters slack workspace, it will be saved and displayed in the context menu.

<img width="694" alt="2019-01-20 1 45 45" src="https://user-images.githubusercontent.com/603523/51429752-24feff80-1c55-11e9-9684-64f028912d05.png">

**Comment by takanakahiko** [comment]
Related : #1
