### ISSUE TITLE
unable to cancel Emoji addition process

### ISSUE THREAD

**Issue by zenmaibane** [takanakahiko/slack-emoji-meister#6]
Currently,  _slack-emoji-meister_ is unable to cancel Emoji addition process.

So, When users use this function by mistake, they feel uncomfortable.

![pose](https://user-images.githubusercontent.com/16816304/51190233-1f3bae00-1925-11e9-9e5e-1b533e977e72.gif)

**Comment by takanakahiko** [comment]
@zenmaibane  Thank you for your report!
PRs welcome.
